---
- name: Install containerd package
  apt:
    name: containerd.io
    state: present
    update_cache: yes

- name: Ensure containerd config directory exists
  file:
    path: /etc/containerd
    state: directory

- name: Generate default containerd configuration
  command: containerd config default
  register: containerd_config_default
  changed_when: false

- name: Write default containerd configuration
  copy:
    content: "{{ containerd_config_default.stdout }}"
    dest: /etc/containerd/config.toml

- name: Set containerd cgroup driver to systemd
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    line: '            SystemdCgroup = true'
  notify: Restart containerd # Triggers the handler defined in setup-cluster.yml

- name: Ensure containerd service is started and enabled
  systemd:
    name: containerd
    state: started
    enabled: yes

# Handlers block removed from here
